#!/bin/bash

INIT_NODE=${HOST_ENGULA_1}
DEPLOY_DIR=

# ${DEPLOY_DIR}/${LOG_DIR}/xxx.log
LOG_DIR=

# eg: https://xxx/engula-v0.1.1.xxx.tar.gz
# BASE_URL=https://xxx
# PACKAGE_NAME=engula-v0.1.1
BASE_URL=
PACKAGE_NAME=
PACKAGE_URL=${BASE_URL}/${PACKAGE_NAME}.tar.gz

# If not set, sha256 will not be checked and the tarball will be re-downloaded every download.
PACKAGE_SHA256_SUM=

ENABLE_TCMALLOC=true
TCMALLOC_MAX_TOTAL_THREAD_CACHE_BYTES=
